name: Cucumber API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  cucumber:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Cucumber Test Execution
      env:
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
          BASE_URI: ${{ secrets.BASE_URI }}
      run: mvn clean test -Dsuite=suite-cucumber
    - name: Upload Cucumber Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
       name: cucumber-reports
       path: |
          target/cucumber-report.html
          target/cucumber.json
